server:
  port: 8200
spring:
    application:
        name: bdkt-service-weixin
    profiles:
      active: ${BDKT_ACTIVE:pro}
---
spring:
  profiles: local
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://bdkt:vipbdkt@localhost:8100/eureka
    registry-fetch-interval-seconds: 10
yang: yzxlocal
---
spring:
  profiles: dev
eureka:
  instance:
    #prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://bdkt:vipbdkt@eureka.baidukt.com:8100/eureka
    registry-fetch-interval-seconds: 10
swagger:
  authorization:
    type:
yang: yzx
---
spring:
  profiles: pro
app:
  id: bdkt-service-weixin
apollo:
  meta: http://apollo.baidukt.com:8080
eureka:
  instance:
    #prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://bdkt:vipbdkt@eureka.baidukt.com:8100/eureka
    registry-fetch-interval-seconds: 10

