server:
  port: 8300
spring:
    application:
        name: bdkt-service-member
    profiles:
      active: ${BDKT_ACTIVE:pro}
---
spring:
  profiles: local
eureka:
  instance:
    #prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://bdkt:vipbdkt@localhost:8100/eureka
    registry-fetch-interval-seconds: 10
---
spring:
  profiles: dev
eureka:
  instance:
    #prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://bdkt:vipbdkt@eureka.baidukt.com:8100/eureka
    registry-fetch-interval-seconds: 10
---
spring:
  profiles: pro
app:
  id: bdkt-service-member
apollo:
  meta: http://apollo.baidukt.com:8080
eureka:
  instance:
    #prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://bdkt:vipbdkt@eureka.baidukt.com:8100/eureka
    registry-fetch-interval-seconds: 10

